#### 1. Import NumPy

Make sure to follow the conventions!

In [3]:
# Your code here
import numpy as np

#### 2. Create an array of 10 zeros 

In [4]:
# Your code here
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
# Expected output

#### 3. Create an array of 10 ones

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
# Expected output

#### 4. Create an array of 10 fives

In [8]:
np.full(10,5.0)
np.repeat(5.0,10)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [9]:
# Expected output

#### 5. Create a vector, named `arr`, of 10 zeros the fifth value of which is 1.

In [10]:
arr=np.zeros(10)
arr[4]=1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [11]:
# Expected output

#### 6. Create an array of the integers from 10 to 50

In [12]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [13]:
# Expected output

#### 7. Reverse an array in **TWO** ways: using 'the Python way' and using a NumPy function

In [14]:
arr = np.array([1, 2, 3])
print('Using the Python way:',arr[::-1])
print('Using a NumPy function:',np.flip(arr))
# Your code here

Using the Python way: [3 2 1]
Using a NumPy function: [3 2 1]


In [15]:
# Expected output

#### 8. Create a 5x5 array with 1 on the border and 0 inside

In [16]:
#first way
arr=np.ones((5,5))
arr[1:-1,1:-1]=np.zeros((3,3))
arr
#second way
np.pad(np.zeros((3,3)),(1,1),constant_values=(1,1))

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
# Expected output

#### 9. Add a border filled with 0's on the two sides of an array.

> Hint: [np.pad](https://numpy.org/doc/stable/reference/generated/numpy.pad.html)

In [18]:
arr = np.array([1, 2, 3])
np.pad(arr,(1,1),'constant', constant_values=(0, 0))


array([0, 1, 2, 3, 0])

In [19]:
# Expected output

#### 10. Create an array of all the even integers from 10 to 50

In [20]:
#first way
np.arange(10,51,2)

#second way
arr=np.arange(10,51)
arr[arr%2==0]


array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [21]:
# Expected output

#### 11. Create a 3x3 matrix with values ranging from 0 to 8

In [22]:
np.reshape(np.arange(0,9),(3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
# Expected output

#### 12. Create a 3x3 identity matrix

In [24]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
# Expected output

#### 13. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

> Hint: [np.diag](https://numpy.org/doc/stable/reference/generated/numpy.diag.html)

In [26]:
np.diagflat([1,2,3,4],-1)


array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [27]:
# Expected output

#### 14. Use NumPy to generate a random number between 0 and 1

**Note**: Your result's value should be different from the one shown below.

In [28]:
np.random.rand(1)

array([0.560229])

In [29]:
# Expected output

#### 15. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

**Note**: Your result's values should be different from the ones shown below.

In [30]:
np.random.normal(loc=0,scale=1,size=25)

array([-0.02195844,  1.33654619, -0.40409304,  0.27474361, -0.09792755,
       -0.29394661, -0.86521856,  1.00044744, -0.80563144,  0.06742698,
        1.3167729 ,  2.30261868,  0.55812543,  0.57333051, -0.82380145,
        0.30890014,  0.01634773, -0.64541609, -0.32450401, -0.95408878,
        1.84575507,  1.21588046, -0.1892542 , -0.72141066,  0.70606098])

In [31]:
# Expected output

#### 16. Create a 3x3x3 array with random values drawn from the uniform distribution

**Note**: Your result's values should be different from the ones shown below.


In [32]:
np.random.uniform(size=(3,3,3))

array([[[0.93739318, 0.55305937, 0.96326854],
        [0.99506036, 0.89260846, 0.84452781],
        [0.56545763, 0.3417639 , 0.06852618]],

       [[0.73529261, 0.42015732, 0.20191216],
        [0.7641389 , 0.68533264, 0.56752298],
        [0.84383003, 0.81312   , 0.30230328]],

       [[0.16364783, 0.07634254, 0.20378762],
        [0.79466992, 0.22041072, 0.3558448 ],
        [0.22473853, 0.05284974, 0.62123753]]])

In [33]:
# Expected output

#### 17. Create a 10x10 array with random values drawn from the uniform distribution and find the minimum and maximum values.

**Note**: Your result's values should be different from the ones shown below.

In [34]:
arr=np.random.uniform(size=(10,10))
print('The array:',arr)
print('Its min value:',np.min(arr))
print('Its max value:',np.max(arr))

The array: [[0.18016108 0.57806986 0.21906083 0.55810167 0.66335537 0.45723963
  0.94058252 0.37657047 0.29215952 0.32364273]
 [0.3649484  0.78853032 0.24031565 0.35695293 0.24175109 0.30293094
  0.42599092 0.32065299 0.58871567 0.79567513]
 [0.05130381 0.07712378 0.84933919 0.74656958 0.20210267 0.21905275
  0.76415228 0.38737199 0.50570608 0.81272032]
 [0.98940795 0.24551095 0.52783558 0.91893149 0.7965315  0.31991763
  0.48646819 0.90616571 0.11677502 0.32477144]
 [0.01755657 0.7406168  0.34140129 0.45936053 0.13830291 0.20869326
  0.70804577 0.35724819 0.8948388  0.35579073]
 [0.40039518 0.48680589 0.75482209 0.27965838 0.72025648 0.86455127
  0.57066888 0.47606883 0.64983303 0.2640256 ]
 [0.69856923 0.73138221 0.94836447 0.96366802 0.95920224 0.511631
  0.81970492 0.89240611 0.46943728 0.14663731]
 [0.5024492  0.1724636  0.45344115 0.77950883 0.6604813  0.10468172
  0.89048702 0.43111369 0.3263888  0.06705647]
 [0.04450881 0.87122082 0.20304758 0.2360255  0.36939832 0.01320955
  0

In [35]:
# Expected output

#### 18. Create a random array with values drawn from the uniform distribution of size 30 and find the mean value

In [36]:
arr=np.random.uniform(size=30)
print('The array:',arr)
print('Its mean:',np.mean(arr))

The array: [0.24333985 0.81261688 0.7878266  0.07519082 0.3180317  0.16497768
 0.24558169 0.61049165 0.85353051 0.0122489  0.71034446 0.63277144
 0.36318708 0.06839862 0.63439811 0.29666807 0.48012527 0.51347341
 0.21884022 0.60067067 0.15762875 0.74365925 0.54818701 0.18202268
 0.44110861 0.60014619 0.19869097 0.92668034 0.49946202 0.43439537]
Its mean: 0.4458231597040353


In [37]:
# Expected output

#### 19. Create the following matrix:

In [61]:
np.arange(0.01,1.01,0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [38]:
# Expected output

#### 20. Create an array of 20 linearly spaced points between 0 and 1:

In [59]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [39]:
# Expected output

## Numpy Indexing and Selection

Now you will be given a starting matrix (be sure to run the cell below!), and be asked to replicate the resulting matrix outputs.

In all of the solutions until the last task before the section `NumPy Operations` you should be using `mat`.

In [62]:
# RUN THIS CELL - THIS IS OUR STARTING MATRIX
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 21. Write code that reproduces the output shown below.

In [63]:
# CODE HERE
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [42]:
# Expected output

#### 22. Write code that reproduces the output shown below.

In [66]:
mat[3,4]
mat[mat==20]

array([20])

In [43]:
# Expected output

#### 23. Write code that reproduces the output shown below.

In [72]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [44]:
# Expected output

#### 24. Write code that reproduces the output shown below.

In [74]:
mat[-1,]

array([21, 22, 23, 24, 25])

In [45]:
# Expected output

#### 25. Write code that reproduces the output shown below.

In [75]:
mat[-2:,]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [46]:
# Expected output

#### 26. Find the indices of the non-zero elements in the provided array.

In [81]:
arr = np.array([1,2,0,0,4,0])

# Your code here
np.where(arr!=0)[0]

(array([0, 1, 4]),)

In [48]:
# Expected output

## NumPy Operations

#### 27. Get the sum of all the values in mat

In [82]:
np.sum(mat)

np.int64(325)

In [49]:
# Expected output

#### 28. Get the standard deviation of the values in mat

In [83]:
np.std(mat)

np.float64(7.211102550927978)

In [50]:
# Expected output

#### 29. Get the sum of all the columns in mat

In [85]:
np.sum(mat,axis=0)

array([55, 60, 65, 70, 75])

In [51]:
# Expected output

#### 30. Create and multiply a 5x3 matrix by a 3x2 matrix (matrix product). The matrices can hold random values or you can create them manually.

**Note**: In this example output the matrices held random values, so your result's values should be different from the ones shown below.

In [92]:

np.matmul(np.arange(0,5*3).reshape(5,3),np.arange(0,3*2).reshape(3,2))

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

In [52]:
# Expected output

#### 31. Create a 1D array of random integers between 0 and 9. Negate all elements which are between 3 and 8.

In [105]:
arr=np.random.randint(0,10,size=15)
arr[(arr>=3) & (arr<=8)]*=-1
arr

array([-8, -3, -4, -6,  2,  0, -6,  9, -7, -5,  9, -3,  9, -6, -3],
      dtype=int32)

In [53]:
# Expected output

#### 32. Create a random array of size 10 and sort it

In [110]:
np.sort(np.random.randint(0,100,size=100))

array([ 1,  1,  4,  4,  4,  5,  7,  9,  9, 11, 12, 13, 13, 14, 15, 16, 16,
       16, 16, 16, 18, 20, 21, 23, 23, 24, 25, 26, 26, 28, 28, 28, 30, 31,
       32, 32, 33, 34, 35, 38, 38, 39, 39, 39, 40, 41, 44, 47, 48, 48, 48,
       48, 49, 50, 51, 53, 54, 55, 57, 57, 57, 58, 58, 60, 60, 62, 62, 63,
       67, 68, 70, 70, 71, 73, 74, 74, 75, 75, 76, 77, 78, 79, 82, 84, 85,
       86, 88, 90, 90, 90, 91, 92, 92, 94, 94, 94, 95, 98, 99, 99],
      dtype=int32)

In [54]:
# Expected output

#### 33. Create random vector of values drawn from the uniform distribution of size 10 and replace the maximum value by 0

In [118]:
arr=np.random.uniform(size=10)
arr[arr==np.max(arr)]=0
arr

array([0.43308496, 0.84160437, 0.        , 0.16667603, 0.29709214,
       0.78105524, 0.91795162, 0.64982794, 0.32734857, 0.09183038])

In [55]:
# Expected output

#### 34. What function can we use to ensure that we always get the same random numbers?

> **Your answer**: np.random.rand()